In [1]:
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split#split
from sklearn.neighbors import KNeighborsClassifier#model = KNeighborsClassifier()
iris = datasets.load_iris()#高度统一，如datasets.load_boston()
iris_X = iris.data#注意没有括号，都仅是一个属性
iris_y = iris.target

In [2]:
print(iris_X[:2,:])#取两个数据，属性行展开,第一维默认是None,数据个数
print(iris_y)
len(iris_y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


150

In [7]:
X_train,X_test,y_train,y_test = train_test_split(iris_X,iris_y,test_size=0.2)#8比2分隔
print(y_test)#并做了乱序
len(y_test)

[0 2 2 1 0 2 1 1 0 2 1 0 2 1 1 1 0 2 2 1 1 2 1 1 1 2 0 0 1 2]


30

In [17]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
print(knn.predict(X_test))#model.predict返回预测的y数组
print(y_test)
print(knn.score(X_test,y_test))

[1 2 0 0 1 0 0 1 0 2 0 1 0 2 2 0 0 1 1 1 2 1 1 0 0 2 0 2 2 1]
[1 2 0 0 1 0 0 1 0 2 0 1 0 2 2 0 0 1 2 1 2 1 1 0 0 2 0 2 2 1]
0.9666666666666667


In [6]:
from sklearn.model_selection import cross_val_score
knn = KNeighborsClassifier(n_neighbors=120)
#跳过划分好的数据，用提取的iris进行交叉验证
score = cross_val_score(knn,iris_X,iris_y,cv=5,scoring="accuracy")
print(score)#5次交叉验证
print(score.mean())

[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
0.3333333333333333


In [5]:
##自己计算accuracy的方法
predict = knn.predict(X_test)
acc = tf.reduce_mean(tf.cast(tf.equal(predict,y_test),dtype=tf.float32))
sess = tf.Session()
print(sess.run(acc))
print(knn.score(X_test,y_test))

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.